### ISSUE TITLE
Does not work with Groovy V3 (UCD 7.2.1 or newer)

### ISSUE THREAD

**Issue by osmanburucu-ibm** [UrbanCode/Ansible-Toolkit-UCD#5]
Step is working with older UCD Agent version and Groovy V2.x, but as soon a newer UCD agent (7.2.1 or newer) with Groovy V3 is used i get this error message:

```
org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
file:/opt/ucd/agent/var/plugins/com.urbancode.air.plugin.AnsibleToolkit_53_64fea7060cb6109785ac23130dd0820245a7b0a452098e29b4fbbbfe57ca65c1/classes/com/urbancode/air/AirPluginTool.groovy: 34: The variable [inputPropsStream] is declared final but is reassigned
. At [34:13]  @ line 34, column 13.
               inputPropsStream = new FileInputStream(inputPropsFile);
               ^

1 error
```

[stdOut.txt](https://github.com/UrbanCode/Ansible-Toolkit-UCD/files/8598948/stdOut.txt)
![Screenshot 2022-05-01 at 15 03 20](https://user-images.githubusercontent.com/58933456/166147262-198e6c7a-5291-450b-adec-749e4acbd0fe.png)

**Comment by AnilSetty** [comment]
@osmanburucu-ibm ,
The issue has been fixed, and the new plugin version has been released. Please use the updated version to resume plugin operations as usual.
The fixed plugin will be available in the 'Releases' section and will also be shared here.
https://github.com/UrbanCode/Ansible-Toolkit-UCD/releases/tag/54.aaf961a

**Comment by AnilSetty** [comment]
A plugin has been provided to address the issue.

**Comment by osmanburucu-ibm** [comment]
A great Thank You!

Cheers
OZ

Sincerely,

Ing. Osman Burucu
Sr. Product Manager

IBM DevOps Automation
+43 664 6186507 Mobile
+43 1 21145 4746 Office
***@***.******@***.***>

IBM Let’s create a better software delivery experience
Out-Of-Office-Notification:

  *   November 1, November 8, November 22
  *   December 21 to January 6


From: AnilSetty ***@***.***>
Date: Tuesday, 19. November 2024 at 15:46
To: UrbanCode/Ansible-Toolkit-UCD ***@***.***>
Cc: Osman Burucu ***@***.***>, Mention ***@***.***>
Subject: [EXTERNAL] Re: [UrbanCode/Ansible-Toolkit-UCD] Does not work with Groovy V3 (UCD 7.2.1 or newer) (Issue #5)
@ osmanburucu-ibm , The issue has been fixed, and the new plugin version has been released. Please use the updated version to resume plugin operations as usual. The fixed plugin will be available in the 'Releases' section and will also be shared


@osmanburucu-ibm<https://github.com/osmanburucu-ibm > ,
The issue has been fixed, and the new plugin version has been released. Please use the updated version to resume plugin operations as usual.
The fixed plugin will be available in the 'Releases' section and will also be shared here.
https://github.com/UrbanCode/Ansible-Toolkit-UCD/releases/tag/54.aaf961a<https://github.com/UrbanCode/Ansible-Toolkit-UCD/releases/tag/54.aaf961a >
